version: 2.1

orbs:
  python: cjw296/python-ci@3.1

jobs:
  release:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: "Install Project"
          command: pip install .[build]
      - run:
          name: "Release"
          command: carthorse --config .carthorse.yml

common: &common
  jobs:

    - python/pip-run-tests:
        matrix:
          parameters:
            image:
              - cimg/python:3.10
        command: pytest --cov carthorse --cov tests

    - python/coverage:
        name: coverage
        requires:
          - python/pip-run-tests

    - release:
        requires:
          - coverage
        filters:
          branches:
            only: master

workflows:
  push:
    <<: *common
  periodic:
    <<: *common
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
